### ISSUE TITLE
Null pointer exception: educatorMainPanel

### ISSUE THREAD

**Issue by 62696e617279** [62696e617279/educatorProductivityToolkit#1]
Blocked in authentication process:
- Student user works as expected
- Guest or Instructor authentication does not work even though the process is the same. Returns a null JPanel named educatorMainPanel. 

Each user has a "Status" code in the excel document. I am using this code in a switch to determine which class to instantiate (student, guest, or instructor). It also determines which background image to display. This latter part is working.

When the status char is 'S' everything works - the user ID and panel display on authentication and the correct image is used. When the char is 'I' or 'G' - the correct image loads but it never displays as the panel is null. 

# Stack Trace: 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at com.arcologydesigns.Views.EducatorMainForm.createAndShowGUI(EducatorMainForm.java:61)
at com.arcologydesigns.Views.EducatorMainForm.<init>(EducatorMainForm.java:36)
com.arcologydesigns.Views.AuthenticationForm$2.actionPerformed(AuthenticationForm.java:91)

Edit: 
### Possible Resolution:
Added { educatorMainPanel.setSize(300,300); } to EducatorMainForm constructor and it seems to work - instructors and guests are authenticated and the correct panel, user ID, and image show. I am not sure if this is correct or why it works. Leaving issue open for now

**Comment by bss8** [comment]
Closed as out of date / no longer applicable.
