### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by 62696e617279** [62696e617279/educatorProductivityToolkit#3]
IO Exception on reading file: java.io.FileNotFoundException: .\resources\flatFiles\studentData.txt 
(The system cannot find the path specified)

### Possible fix: 
ClassLoader cldr = this.getClass().getClassLoader();
java.net.URL fileURL   = cldr.getResource("flatFiles/studentData.txt");
// app logic

**Comment by bss8** [comment]
```
  // Set a background for JFrame
  ClassLoader cldr = this.getClass().getClassLoader();
  URL imageURL = cldr.getResource("images/desert.jpg");

  assert imageURL != null;  //used during debugging

  if (imageURL != null) {
     img = new ImageIcon(imageURL);
  }
  setContentPane(new JLabel(img));
```

 /*
         EXAMPLE OF BAD CODE: the below code. To fetch a resource, use the absolute reference path and invoke
         getClassLoader() then getResource() to set a resource. Otherwise, the resource will not show when running
         the application from a JAR file.
            setContentPane(new JLabel(new ImageIcon(".\resources\desert.jpg")));
      */
